# Generated by Django 4.2.11 on 2024-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artistprofile_alter_album_artist_delete_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
