# Generated by Django 4.2.11 on 2024-04-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_artistprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='Brano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_index', models.PositiveIntegerField()),
                ('side', models.CharField(blank=True, max_length=2, null=True)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brani', to='music.album')),
            ],
            options={
                'ordering': ['album', 'track_index', 'side'],
                'unique_together': {('album', 'track_index')},
            },
        ),
    ]
