# Generated by Django 4.2.11 on 2024-04-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_artistprofile_name_brano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brano',
            options={'ordering': ['album', 'side', 'track_index']},
        ),
        migrations.AlterUniqueTogether(
            name='brano',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='brano',
            name='side',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='brano',
            unique_together={('album', 'track_index', 'side')},
        ),
    ]
