# Generated by Django 4.2.11 on 2024-04-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_brano_options_alter_brano_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
        migrations.AlterField(
            model_name='brano',
            name='side',
            field=models.PositiveIntegerField(),
        ),
    ]
