# Generated by Django 4.2.11 on 2024-04-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_brano_mp3_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brano',
            name='mp3_file',
        ),
        migrations.AddField(
            model_name='brano',
            name='mp3_file_path',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
