# Generated by Django 4.2.11 on 2024-04-23 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_brano_mp3_file_path_brano_mp3_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file', models.FileField(upload_to='sheet_music_files/')),
                ('Complexity', models.IntegerField(choices=[(1, '1 - Molto semplice'), (2, '2 - Semplice'), (3, '3 - Moderato'), (4, '4 - Complesso'), (5, '5 - Molto complesso')])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_music', to='music.artistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='merch_images/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchandise', to='music.artistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='instrument_images/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='music.artistprofile')),
            ],
        ),
    ]
