# Generated by Django 4.2.11 on 2024-04-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_sheetmusic_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
