# Generated by Django 4.2.11 on 2024-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_delete_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='photo_image',
            field=models.ImageField(blank=True, null=True, upload_to='photo_users/'),
        ),
    ]
