# Generated by Django 4.2.11 on 2024-04-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_album_creation_date_artistprofile_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='brano',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sheetmusic',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
