# Generated by Django 4.2.11 on 2024-04-25 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_remove_artistprofile_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brano',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='brano',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brani', to='music.artistprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='brano',
            unique_together={('album', 'track_index', 'side', 'artist')},
        ),
        migrations.RemoveField(
            model_name='brano',
            name='creation_date',
        ),
    ]
