# Generated by Django 4.2.11 on 2024-04-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_brano_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brano',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
