# Generated by Django 4.2.11 on 2024-04-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_alter_brano_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
