# Generated by Django 4.2.11 on 2024-04-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_alter_album_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
