# Generated by Django 4.2.11 on 2024-04-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_genre_alter_album_genre'),
    ]

    operations = [
    ]
