# Generated by Django 4.2.11 on 2024-05-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_remove_artistprofile_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/'),
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/'),
        ),
    ]
