# Generated by Django 4.2.11 on 2024-05-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0035_remove_artistprofile_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='name',
            field=models.CharField(default='Unknown', max_length=120),
        ),
        migrations.AlterField(
            model_name='listenerprofile',
            name='name',
            field=models.CharField(default='Unknown', max_length=120),
        ),
    ]
