# Generated by Django 4.2.11 on 2024-06-21 21:04

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0037_remove_album_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brano',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to=music.models.upload_to),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('artist', 'title')},
        ),
    ]
