# Generated by Django 4.2.11 on 2024-06-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0038_alter_brano_mp3_file_alter_album_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='creation_date',
        ),
    ]
