# Generated by Django 4.2.11 on 2024-07-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0040_alter_follow_follower_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='playlist_covers/')),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='music.listenerprofile')),
            ],
            options={
                'unique_together': {('listener', 'title')},
            },
        ),
        migrations.AddField(
            model_name='brano',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.playlist'),
        ),
    ]
