# Generated by Django 4.2.11 on 2024-07-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0042_alter_playlist_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
