# Generated by Django 4.2.11 on 2024-07-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0043_alter_playlist_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brano',
            name='playlist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='music.brano'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='listener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='music.listenerprofile'),
        ),
    ]
