# Generated by Django 4.2.11 on 2024-08-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0047_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
