# Generated by Django 4.2.11 on 2024-08-22 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0049_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='artist',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='music.artistprofile'),
            preserve_default=False,
        ),
    ]
