# Generated by Django 4.2.11 on 2024-08-22 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0050_order_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='artist',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='music.listenerprofile'),
            preserve_default=False,
        ),
    ]
