# Generated by Django 4.2.11 on 2024-08-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0052_alter_order_buyer_alter_order_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='reservation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
