# Generated by Django 4.2.11 on 2024-08-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0054_remove_merchandise_reservation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
