# Generated by Django 4.2.11 on 2024-08-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0055_merchandise_reserved_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='reserved_quantity',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
