# Generated by Django 4.2.11 on 2024-08-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0056_remove_merchandise_reserved_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='reservation_expires_at',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='original_stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
