# Generated by Django 4.2.11 on 2024-08-23 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0057_remove_merchandise_reservation_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reservation_expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 17, 30, 22, 405308, tzinfo=datetime.timezone.utc)),
        ),
    ]
