# Generated by Django 4.2.11 on 2024-08-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0058_order_reservation_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reservation_expiration',
        ),
    ]
