# Generated by Django 4.2.11 on 2024-08-25 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0059_remove_order_reservation_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempOrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('reservation_expiration', models.DateTimeField()),
                ('merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.merchandise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
