# Generated by Django 4.2.11 on 2024-08-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0062_order_shipping_address_order_shipping_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default=41121, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zip',
            field=models.CharField(max_length=10),
        ),
    ]
