# Generated by Django 4.2.11 on 2024-08-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0064_alter_notification_options_remove_notification_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
