# Generated by Django 4.2.11 on 2024-09-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0067_alter_album_published_likedplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brano',
            name='title',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('comment', 'Comment'), ('album', 'Album'), ('like_playlist', 'Like Playlist')], max_length=20),
        ),
    ]
