# Generated by Django 4.2.11 on 2024-09-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0073_delete_followlistener'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Brano', 'verbose_name_plural': 'Brani'},
        ),
    ]
