# Generated by Django 4.2.11 on 2024-09-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0075_alter_brano_options_alter_playlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brano',
            options={'ordering': ['album', 'side', 'track_index'], 'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
    ]
